// Generated by CoffeeScript 1.6.3
var _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Raffler.Models.Entry = (function(_super) {
  __extends(Entry, _super);

  function Entry() {
    _ref = Entry.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Entry.prototype.defaults = {
    name: null,
    winner: false
  };

  return Entry;

})(Backbone.Model);

Raffler.Collections.Entries = (function(_super) {
  __extends(Entries, _super);

  function Entries() {
    _ref1 = Entries.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  Entries.prototype.model = Raffler.Models.Entry;

  Entries.prototype.localStorage = new Store("backbone-coffee-raffle");

  return Entries;

})(Backbone.Collection);
